### ISSUE TITLE
Handle / research UNBLOCKED aioredis error

### ISSUE THREAD

**Issue by bsergean** [machinezone/cobra#3]
```
[4b166ffa::pubsub] UNBLOCKED force unblock from blocking operation, instance state changed (master -> replica?)
[4b166ffa::pubsub] Generic Exception caught in Traceback (most recent call last):
  File "/cobras/server/redis_subscriber.py", line 52, in redisSubscriber
    latest_ids=[lastId])
  File "/usr/local/lib/python3.7/site-packages/aioredis/util.py", line 55, in wait_convert
    result = await fut
aioredis.errors.ReplyError: UNBLOCKED force unblock from blocking operation, instance state changed (master -> replica?)

[4b166ffa::pubsub] Closing redis subscription
```

**Comment by bsergean** [comment]
Maybe it is about calling xread without a timeout

-> https://redis.io/commands/client-unblock

**Comment by kristoff-it** [comment]
Judging from the error message, it seems that Redis unblocked that command forcefully. The command that you refer to, is for allowing you to unblock a client manually via a command, but the error message would be different in that case.

The error message seems to suggest that it's possible that the Redis server you are connected to lost its master status and became a replica. If you were using XREADGROUP it would make sense because it's an operation that changes the state of Redis (by assigning a message to a specific consumer), but XREAD is truly a read-only command. 

There might be some other factor that I'm not aware of, but it seems that this could be improved in Redis. See the corresponding code: https://github.com/antirez/redis/blob/ae8cab3296e71df1130aec59c679d682bec440ae/src/blocked.c#L214

I've opened an issue about this https://github.com/antirez/redis/issues/6371.

**Comment by bsergean** [comment]
Thanks for the investigation. In my case it might be because redis was being hammered and ran out of memory, or was restarted automatically. I reverted the code change that triggered the big increase in redis write (XADD) and that error went away.

In my current 'cluster' (not a proper redis cluster, just a set of redis machines), only one of those was rebooted automatically by kubernete in the last 18 days.
